[metadata]
name = cicm
version = 0.1.0
description = Cross-image co-occurrence matrix (CICM) implementation in Python.
author = Victor Medina
license = MIT
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/vjmedina/CICM

[options]
package_dir =
    = src
packages = find:
install_requires =
    numpy
    scikit-image

[options.packages.find]
where = src
